# -*- coding: utf-8 -*-
"""KNN.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RQPrP8uAnNWNutbDoOqCN84vRCi9oFpl
"""

import numpy as np
import pandas as pd

def distance(x,X):
  return np.sqrt(np.sum((x-X)**2))
def KNN(X,Y,x,K=10):
  m = X.shape[0]
  val = []
  for i in range(m):
    xi = X[i]
    dist = distance(x,xi)
    val.append((dist,Y[i]))
    val = sorted(val,key = lambda x:x[0])[:K]
    val = np.asarray(val)
    new_vals = np.unique(val[:,1],return_counts=True)
    index = new_vals[1].argmax()
    output = new_vals[0][index]
  return output 
data = pd.read_csv("sample_data/mnist_train_small.csv")
X = data.iloc[:,1:]
Y = data.iloc[:,0]
X,Y
output = KNN(X,Y,x,K=10)
output

